# Generated by Django 4.0.2 on 2022-03-10 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('room_num', models.IntegerField()),
                ('user_num', models.IntegerField()),
                ('category', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=50)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('coworker', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='start')),
                ('end_date', models.DateTimeField(verbose_name='end')),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updates', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('master', models.IntegerField()),
                ('title', models.CharField(max_length=45)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updates', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('profile', models.CharField(max_length=150, null=True)),
                ('nickname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updates', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='user_in_room',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('room_num', models.IntegerField()),
                ('user_num', models.IntegerField()),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updates', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
            ],
        ),
    ]
