# Generated by Django 4.0.2 on 2022-03-22 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('master', models.IntegerField()),
                ('title', models.CharField(max_length=45)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updates', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('nickname', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updates', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='UserInRoom',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updates', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
                ('room_num', models.ForeignKey(db_column='room_num', on_delete=django.db.models.deletion.CASCADE, to='scheduler.room')),
                ('user_num', models.ForeignKey(db_column='user_num', on_delete=django.db.models.deletion.CASCADE, to='scheduler.user')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('user_num', models.IntegerField()),
                ('category', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=50)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('coworker', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='start')),
                ('end_date', models.DateTimeField(verbose_name='end')),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updates', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
                ('room_num', models.ForeignKey(db_column='room_num', on_delete=django.db.models.deletion.CASCADE, to='scheduler.room')),
            ],
        ),
    ]
