# Generated by Django 4.0.2 on 2022-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_calendar_num_alter_room_num_alter_user_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end_date',
            field=models.DateField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.DateField(verbose_name='start'),
        ),
    ]
