# Generated by Django 4.0.2 on 2022-03-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_calendar_end_date_alter_calendar_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end_date',
            field=models.DateTimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.DateTimeField(verbose_name='start'),
        ),
    ]
