# Generated by Django 4.0.2 on 2022-03-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_userinroom_room_num_alter_userinroom_user_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='allday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
