# Generated by Django 4.0.2 on 2022-03-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_calendar_allday_calendar_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='allday',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='start_time',
        ),
    ]
